### ISSUE TITLE
Unable to find keys in checkpoint

### ISSUE THREAD

**Issue by yaylinda** [greydanus/scribe#6]
So I downloaded the model from your google drive file, and ran the command from the README, however, I am getting errors saying several keys are not found in the checkpoint file. Any ideas?

```
SAMPLING MODE...
loading data...
building model...
	using alphabet abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
2017-11-06 15:22:18.599963: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-06 15:22:18.599998: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-11-06 15:22:18.600003: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-06 15:22:18.600007: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
attempt to load saved model...
2017-11-06 15:22:19.147508: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell0/lstm_cell/bias/RMSProp_1 not found in checkpoint
2017-11-06 15:22:19.147508: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell0/lstm_cell/kernel not found in checkpoint
2017-11-06 15:22:19.147531: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell0/lstm_cell/bias/RMSProp not found in checkpoint
2017-11-06 15:22:19.147531: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell0/lstm_cell/bias not found in checkpoint
2017-11-06 15:22:19.148667: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell0/lstm_cell/kernel/RMSProp not found in checkpoint
2017-11-06 15:22:19.148974: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell0/lstm_cell/kernel/RMSProp_1 not found in checkpoint
2017-11-06 15:22:19.149021: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell1/lstm_cell/bias/RMSProp_1 not found in checkpoint
2017-11-06 15:22:19.149158: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell1/lstm_cell/kernel not found in checkpoint
2017-11-06 15:22:19.149188: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell1/lstm_cell/bias not found in checkpoint
2017-11-06 15:22:19.149322: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell1/lstm_cell/kernel/RMSProp not found in checkpoint
2017-11-06 15:22:19.149756: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell1/lstm_cell/kernel/RMSProp_1 not found in checkpoint
2017-11-06 15:22:19.150055: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell2/lstm_cell/bias not found in checkpoint
2017-11-06 15:22:19.150250: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell2/lstm_cell/kernel/RMSProp not found in checkpoint
2017-11-06 15:22:19.150263: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell2/lstm_cell/bias/RMSProp_1 not found in checkpoint
2017-11-06 15:22:19.150283: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell2/lstm_cell/bias/RMSProp not found in checkpoint
2017-11-06 15:22:19.150464: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell1/lstm_cell/bias/RMSProp not found in checkpoint
2017-11-06 15:22:19.150513: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell2/lstm_cell/kernel not found in checkpoint
2017-11-06 15:22:19.150638: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key cell2/lstm_cell/kernel/RMSProp_1 not found in checkpoint
no saved model to load. starting new session
load failed, sampling canceled
^CTraceback (most recent call last):
  File "run.py", line 152, in <module>
    main()
  File "run.py", line 56, in main
    train_model(args) if args.train else sample_model(args)
  File "run.py", line 148, in sample_model
    time.sleep(args.sleep_time)
KeyboardInterrupt
```

**Comment by jerrydeng** [comment]
You have to use Tensorflow 1.0.0

**Comment by yaylinda** [comment]
I've been able to restore the tf session using the checkpoint and model files that were provided. However, the handwriting output of my text string just doesn't look very good. Even with the text, "You know nothing Jon Snow", that was used in the README. This is what mine looks like: 

![screen shot 2017-11-09 at 2 59 17 pm](https://user-images.githubusercontent.com/10225317/32629376-9fb515b0-c55e-11e7-8264-91b7d4401988.png)

I've tried different styles, biases, tsteps, but it doesn't seem to change anything... the rest of the parameters are model default ones.
